### ISSUE TITLE
Content-Type header cannot contain charset

### ISSUE THREAD

**Issue by jacobjmarks** [microsoft/azure-health-data-services-toolkit#128]
**Describe the bug**
When a request is provided which contains a charset within the Content-Type header &mdash; e.g. `application/fhir+json; charset=utf-8` &mdash; an exception is thrown due to the following line:

https://github.com/microsoft/azure-health-data-services-toolkit/blob/8eef29c9cf7389c67668f2d22c5d5b99e9c70840/src/Microsoft.AzureHealth.DataServices.Core/Pipelines/AzureFunctionExtensions.cs#L42

**Expected behavior**
Requests are handled without issue.

**Actual behavior**
The following exception is thrown:

```
---> System.FormatException: The format of value 'application/fhir+json; charset=utf-8' is invalid.
  at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
  at System.Net.Http.Headers.MediaTypeHeaderValue..ctor(String mediaType)
  at Microsoft.AzureHealth.DataServices.Pipelines.AzureFunctionExtensions.ConvertToHttpRequestMesssage(HttpRequestData req)
  at Microsoft.AzureHealth.DataServices.Pipelines.AzureFunctionPipeline.ExecuteAsync(HttpRequestData request)
  at Bupa.CC.Fhir.Consent.Function.FhirFunction.ConnectedCareFhirHandler(HttpRequestData req, String fhirRoute, FunctionContext executionContext) in /src/src/Bupa.CC.Fhir.Consent.Function/FhirFunction.cs:line 32
  --- End of inner exception stack trace ---
```

**Environment summary**
SDK Version: `1.0.1`
OS Version: Linux
Compute Platform: Azure Function

**Additional context**
Judging by the code, I believe the same issue still exists within the `1.1.0` version of the library. Given that the version bump introduces breaking changes and will require additional efforts to utilise within our project, I believe hotfixes should be published for both current versions.

**Comment by evachen96** [comment]
Hi Jacob! Thanks for submitting this issue, the team will look into it and get back.
