### ISSUE TITLE
Compatibility with Microsoft.Azure.Functions.Worker.Sdk Version 2 and isolated process model

### ISSUE THREAD

**Issue by alexandre-guimond** [microsoft/azure-health-data-services-toolkit#146]
**Describe the bug**
I'm new to this toolkit (and not that experience with Azure) and trying to setup a FHIR proxy using an Azure Function to (ultimatly) add headers and do some input/output filtering. At this point I'm trying to setup a simple pass-through pipeline, but I'm failing. I'm trying to identify the issue, and wondering if the toolkit supports the azure function sdk v2 and isolated process model which I'm using.

The code below fails because of a call to HttpRequestStream.get_Length() (see logs below). I believe this is happening in ConvertToHttpRequestMesssage while doing the conversion from HttpRequestData to HttpRequestMesssage. I gather Length property is not available (throws an exception) for HttpRequestData for Azure Functions sdk v2 and/or with isolated process model.

I might also be doing something wrong. As mentioned, I'm relatively new to this toolkit and Azure...

**To Reproduce**
I've create a simple function app using the standard azure function template from visual studio (.net 9). For simplicify all the code is in the program.cs. (I believe I'm missing a binding for this to actually work, but it's omitted for simplicity at the moment).

using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Builder;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.AzureHealth.DataServices.Configuration;
using Microsoft.AzureHealth.DataServices.Filters;
using Microsoft.AzureHealth.DataServices.Pipelines;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

var builder = FunctionsApplication.CreateBuilder(args);
builder.ConfigureFunctionsWebApplication();
builder.Services
    .UseAzureFunctionPipeline()
    .AddInputFilter(typeof(FhirProxyInputFilter));
builder.Build().Run();

public class Functions(IPipeline<HttpRequestData, HttpResponseData> pipeline, ILogger<Functions> logger)
{
    [Function(nameof(Fhir))]
    public async Task<HttpResponseData> Fhir([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req)
    {
        logger.LogInformation("FHIR pipeline started...");
        return await pipeline.ExecuteAsync(req);
    }
}

public class FhirProxyInputFilter(ILogger<FhirProxyInputFilter> logger) : IInputFilter
{
    private readonly string _id = Guid.NewGuid().ToString();

    public string Id => _id;
    public string Name => "FhirProxyInputFilter";
    public StatusType ExecutionStatusType => StatusType.Normal;
    public event EventHandler<FilterErrorEventArgs>? OnFilterError;

    public Task<OperationContext> ExecuteAsync(OperationContext context)
    {
        try
        {
            return Task.FromResult(context);
        }
        catch (Exception ex)
        {
            logger?.LogError(ex, "Error in {Name}", Name);
            OnFilterError?.Invoke(this, new FilterErrorEventArgs(Name, Id, true));
            return Task.FromResult(context);
        }
    }
}

**Expected behavior**

**Actual behavior**
logs:
[2024-12-24T13:31:01.721Z] Executing 'Functions.Fhir' (Reason='This function was programmatically called via the host APIs.', Id=12b5dd82-9dae-46c8-803b-9e41368d30c6)
[2024-12-24T13:31:04.636Z] FHIR pipeline started...
[2024-12-24T13:31:04.781Z] Function 'Fhir', Invocation id '12b5dd82-9dae-46c8-803b-9e41368d30c6': An exception was thrown by the invocation.
[2024-12-24T13:31:04.785Z] Result: Function 'Fhir', Invocation id '12b5dd82-9dae-46c8-803b-9e41368d30c6': An exception was thrown by the invocation.
Exception: System.NotSupportedException: Specified method is not supported.
[2024-12-24T13:31:04.787Z]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.get_Length()
[2024-12-24T13:31:04.788Z]    at Microsoft.AzureHealth.DataServices.Pipelines.AzureFunctionExtensions.ConvertToHttpRequestMesssage(HttpRequestData req)
[2024-12-24T13:31:04.792Z]    at Microsoft.AzureHealth.DataServices.Pipelines.AzureFunctionPipeline.ExecuteAsync(HttpRequestData request)
[2024-12-24T13:31:04.797Z]    at Functions.Fhir(HttpRequestData req) in C:\Users\guim\OneDrive - humant.io\Source\FunctionApp4\FunctionApp4\Program.cs:line 23
[2024-12-24T13:31:04.801Z]    at FunctionApp4.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\guim\OneDrive - humant.io\Source\FunctionApp4\FunctionApp4\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 38
[2024-12-24T13:31:04.804Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-12-24T13:31:04.809Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 54
[2024-12-24T13:31:04.810Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 96
Stack:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.get_Length()
[2024-12-24T13:31:04.813Z]    at Microsoft.AzureHealth.DataServices.Pipelines.AzureFunctionExtensions.ConvertToHttpRequestMesssage(HttpRequestData req)
[2024-12-24T13:31:04.821Z]    at Microsoft.AzureHealth.DataServices.Pipelines.AzureFunctionPipeline.ExecuteAsync(HttpRequestData request)
[2024-12-24T13:31:04.822Z]    at Functions.Fhir(HttpRequestData req) in C:\Users\guim\OneDrive - humant.io\Source\FunctionApp4\FunctionApp4\Program.cs:line 23
[2024-12-24T13:31:04.824Z]    at FunctionApp4.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\guim\OneDrive - humant.io\Source\FunctionApp4\FunctionApp4\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 38
[2024-12-24T13:31:04.825Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-12-24T13:31:04.828Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 54
[2024-12-24T13:31:04.832Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 96.
[2024-12-24T13:31:04.901Z] Executed 'Functions.Fhir' (Failed, Id=12b5dd82-9dae-46c8-803b-9e41368d30c6, Duration=3232ms)
[2024-12-24T13:31:04.905Z] System.Private.CoreLib: Exception while executing function: Functions.Fhir. System.Private.CoreLib: Result: Failure
Exception: Specified method is not supported.
Stack:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.get_Length()
[2024-12-24T13:31:04.909Z]    at Microsoft.AzureHealth.DataServices.Pipelines.AzureFunctionExtensions.ConvertToHttpRequestMesssage(HttpRequestData req)
[2024-12-24T13:31:04.914Z]    at Microsoft.AzureHealth.DataServices.Pipelines.AzureFunctionPipeline.ExecuteAsync(HttpRequestData request)
[2024-12-24T13:31:04.918Z]    at Functions.Fhir(HttpRequestData req) in C:\Users\guim\OneDrive - humant.io\Source\FunctionApp4\FunctionApp4\Program.cs:line 23
[2024-12-24T13:31:04.922Z]    at FunctionApp4.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\guim\OneDrive - humant.io\Source\FunctionApp4\FunctionApp4\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 38
[2024-12-24T13:31:04.925Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-12-24T13:31:04.928Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 54
[2024-12-24T13:31:04.931Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 96
[2024-12-24T13:31:04.934Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 89.

**Environment summary**
SDK Version: I tried with both 9.0.101 and 8.0.301
OS Version: Windows
Compute Platform: Azure Function (Worker.Sdk Version 2)

**Additional context**

**Comment by evachen96** [comment]
Hi @alexandre-guimond ! Sorry I missed this issue over the holidays. Will have the team look into this and get back to you.

**Comment by evachen96** [comment]
Hi @alexandre-guimond  - The Azure Health Data Services Toolkit is compatible with Microsoft.Azure.Functions.Worker.Sdk version 2 and the isolated process model.

This exception is due to the use of ASP.NET Core pipeline integration within the Azure Functions app, specifically the line:



`builder.ConfigureFunctionsWebApplication();
`


However, the toolkit expects the default Azure Functions request handling, 

Integrating ASP.NET Core's pipeline modifies the request stream in a way that the Toolkit does not support, leading to runtime exceptions such as:



`System.NotSupportedException: Specified method is not supported.
`


To resolve this, please remove the ASP.NET Core pipeline integration (i.e., comment out or delete builder.ConfigureFunctionsWebApplication();) to ensure the default function app pipeline is used.

Thanks!
